### ISSUE TITLE
UTM Thesis template (LateX) 

### ISSUE THREAD

**Issue by Raji-bit** [utmthesis/utmthesis#20]
How can I easily download the lateX form of UTM PhD Thesis template

**Comment by yungszen** [comment]
Hi. Unfortunately, you are asking at the wrong place. This is to lodge issues with the utmthesis package.

You can visit https://people.utm.my/yap/latex/ to learn on latex and you should always google on how to use latex or if you have problems facing with any codes.

For specific questions about utmthesis, you can ask your questions here:
https://groups.google.com/g/utmthesis-discuss?pli=1
